version: "3.2"
services:
  user:
    build: './user/'
    container_name: access-user-service
    #depends_on:
    #  - mysql
    networks:
      - backend
    ports:
      - "127.0.0.1:3000:3000"
  www:
    build: './www2/'
    image: access-www:latest
    container_name: access-www
    #depends_on:
    #  - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
  #mysql:
  #  image: mysql:latest
    #build: './mysql/'
  #  container_name: access-user-db
  #  networks:
  #    - backend
  #  restart: always
  #  environment:
  #    - MYSQL_DATABASE=access
  #    - MYSQL_ROOT_PASSWORD=password
  #  ports:
  #    - "3306:3306"
networks:
  frontend:
  backend: